runtime: python
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
entrypoint: gunicorn -b :$PORT locallibrary.wsgi

beta_settings:
    cloud_sql_instances: endinsat-aventura:us-central1:endinsat-sql

runtime_config:
  python_version: 3

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?log
- ^(.*/)?local_settings.py