# Generated by Django 2.0.1 on 2018-02-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('url_imatge_bandera', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DayInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Day title', max_length=50)),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='departure')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='arrival')),
                ('duration', models.IntegerField(help_text='Duration of the journey in days')),
                ('description', models.TextField(max_length='5000')),
            ],
        ),
        migrations.CreateModel(
            name='Redactor',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth: ')),
                ('description', models.CharField(default='', help_text='Presentet: edat, qui ets? Que busques fer amb aquest blog? Què tagrada...', max_length=5000)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Brief description of the trip', max_length=1000)),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='departure')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='arrival')),
                ('duration', models.IntegerField(default=0, help_text='Duration of the journey in days')),
                ('route_trip_image', models.CharField(default='', help_text='Name of the image file saved in static ex: /images/trip.jpg', max_length=200)),
                ('url_static', models.CharField(default='', help_text='Route from the static folder ex (/static) /marroc (Just the /marroc)', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('e', 'Eye on it'), ('p', 'Planed'), ('o', 'On voyage'), ('d', 'Done')], default='e', help_text='Status of the trip', max_length=1)),
                ('country', models.ManyToManyField(help_text='Select a destiny', to='catalog.Country')),
                ('redactor', models.ManyToManyField(help_text='Select redactor', to='catalog.Redactor')),
            ],
        ),
        migrations.AddField(
            model_name='dayinstance',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Trip'),
        ),
    ]
