# Generated by Django 2.0.1 on 2018-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cant_miss',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_sign',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='country',
            name='traditional_food',
            field=models.CharField(default='', max_length=300),
        ),
    ]
