# Generated by Django 2.0.1 on 2018-01-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180115_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='url_imatge_bandera',
            field=models.CharField(default='', max_length=500),
        ),
    ]
