# Generated by Django 2.0.1 on 2018-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180307_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
