# Generated by Django 2.0.1 on 2018-05-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_redactor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
