# Generated by Django 2.0.1 on 2018-05-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180527_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_image',
        ),
    ]
