# Generated by Django 2.0.1 on 2018-01-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180126_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactor',
            name='description',
            field=models.CharField(default='', help_text='Presentet: edat, qui ets? Que busques fer amb aquest blog? Què tagrada...', max_length=5000),
        ),
    ]
