# Generated by Django 2.0.1 on 2018-05-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_country_flag_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
