# Generated by Django 2.0.1 on 2018-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180527_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayinstance',
            name='day_image',
            field=models.ImageField(default='', upload_to='day'),
        ),
    ]
