# Generated by Django 2.0.1 on 2019-01-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20180630_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='departure')),
                ('arrival_date', models.DateField(blank=True, null=True, verbose_name='arrival')),
                ('duration', models.IntegerField(default=0, help_text='Durada del viatge en dies (aprox)')),
                ('route_trip_image', models.CharField(default='', help_text='Nom de la imatge guardada a la carpeta static ex: /images/trip.jpg', max_length=200)),
                ('url_static', models.CharField(default='', help_text='Ruta a la carpeta /static ex: de "/static/marroc" només "/marroc"', max_length=200)),
                ('status', models.CharField(blank=True, choices=[('e', 'Eye on it'), ('p', 'Planed'), ('o', 'On voyage'), ('d', 'Done')], default='e', help_text='Status of the trip', max_length=1)),
                ('country', models.ManyToManyField(help_text='Selecciona un destí', to='catalog.Country')),
                ('voyagers', models.ManyToManyField(help_text='Escolleix a un viatger', to='catalog.Redactor')),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titol de l'actualització", max_length=50)),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='updateDate')),
                ('description', models.TextField(max_length='5000')),
                ('day_image', models.ImageField(blank=True, upload_to='day')),
                ('travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PlannedTrip')),
            ],
        ),
        migrations.AlterField(
            model_name='dayinstance',
            name='duration',
            field=models.IntegerField(help_text='Durada del viatge en dies'),
        ),
        migrations.AlterField(
            model_name='dayinstance',
            name='title',
            field=models.CharField(help_text='Titol del dia', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ManyToManyField(help_text='Selecciona un destí', to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(default=0, help_text='Durada del viatge en dies'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='redactor',
            field=models.ManyToManyField(help_text='Selecciona un redactor', to='catalog.Redactor'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_trip_image',
            field=models.CharField(default='', help_text='Nom de la imatge guardada a la carpeta static ex: /images/trip.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='url_static',
            field=models.CharField(default='', help_text='Ruta a la carpeta /static ex: de "/static/marroc" només "/marroc"', max_length=200),
        ),
    ]
