# Generated by Django 2.0.1 on 2019-08-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190124_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='url_static',
        ),
        migrations.AddField(
            model_name='trip',
            name='completed',
            field=models.BooleanField(default=False, help_text='El diari està acabat'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imatge hero', upload_to='trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='round_image',
            field=models.ImageField(blank=True, help_text='Imatge rodona', upload_to='trip'),
        ),
    ]
