# Generated by Django 2.0.1 on 2019-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190809_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='url_imatge_bandera',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='route_trip_image',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='status',
        ),
        migrations.RemoveField(
            model_name='plannedtrip',
            name='url_static',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='completed',
            field=models.BooleanField(default=False, help_text='El diari està acabat'),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imatge hero', upload_to='trip'),
        ),
        migrations.AddField(
            model_name='plannedtrip',
            name='round_image',
            field=models.ImageField(blank=True, help_text='Imatge rodona', upload_to='trip'),
        ),
        migrations.AddField(
            model_name='redactor',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imatge hero', upload_to='trip'),
        ),
        migrations.AddField(
            model_name='redactor',
            name='round_image',
            field=models.ImageField(blank=True, help_text='Imatge rodona', upload_to='trip'),
        ),
    ]
