# Generated by Django 2.0.1 on 2019-08-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190809_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='route_trip_image',
        ),
    ]
